-- --------------------------------------------------------
-- Host:                         172.16.148.1
-- Versión del servidor:         5.7.39 - MySQL Community Server (GPL)
-- SO del servidor:              osx10.12
-- HeidiSQL Versión:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Volcando estructura para tabla geslab_canagrosa.adjuntos
CREATE TABLE IF NOT EXISTS `adjuntos` (
  `TIPO` int(11) NOT NULL DEFAULT '0',
  `CODIGO` int(11) NOT NULL DEFAULT '0',
  `ORDEN` int(11) NOT NULL DEFAULT '0',
  `CODIGO_DECODIFICADORA` int(11) NOT NULL DEFAULT '0',
  `ADJUNTO_ID` int(11) DEFAULT NULL,
  `TIPO_DOCUMENTO_ID` int(11) DEFAULT '0',
  `OBSERVACIONES` text,
  `ANULADO` int(11) DEFAULT '0',
  `FILE_NAME` varchar(150) DEFAULT NULL,
  `FILE_SIZE` int(11) DEFAULT '0',
  `FILE_TYPE` varchar(100) DEFAULT NULL,
  `USUARIO_ID` int(11) DEFAULT '0',
  `TIMESTAMP` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `FECHA_CADUCIDAD` date DEFAULT NULL,
  PRIMARY KEY (`TIPO`,`CODIGO`,`ORDEN`),
  KEY `CODIGO_DECODIFICADORA` (`CODIGO_DECODIFICADORA`),
  KEY `ADJUNTO_ID` (`ADJUNTO_ID`),
  KEY `FILE_SIZE` (`FILE_SIZE`),
  KEY `FILE_NAME` (`FILE_NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla geslab_canagrosa.muestras
CREATE TABLE IF NOT EXISTS `muestras` (
  `ID_MUESTRA` int(11) NOT NULL DEFAULT '0',
  `TIPO_MUESTRA_ID` int(11) NOT NULL DEFAULT '0',
  `ID_GENERAL` int(11) NOT NULL DEFAULT '0',
  `ID_PARTICULAR` int(11) NOT NULL DEFAULT '0',
  `ANNO` int(11) NOT NULL DEFAULT '0',
  `TIPO_ANALISIS_ID` int(11) DEFAULT '0',
  `ANALISIS_MODIFICADO` int(11) DEFAULT '0',
  `FECHA_MUESTREO` date DEFAULT NULL,
  `ENTIDAD_MUESTREO_ID` int(11) NOT NULL DEFAULT '0',
  `DETALLE_MUESTREO` varchar(100) DEFAULT '',
  `OBSERVACIONES_MUESTREO` varchar(512) DEFAULT '',
  `FECHA_RECEPCION` date DEFAULT NULL,
  `HORA_RECEPCION` varchar(10) NOT NULL DEFAULT '',
  `EMPLEADO_ID` int(11) NOT NULL DEFAULT '0',
  `FORMATO_ID` int(11) NOT NULL DEFAULT '0',
  `ENTIDAD_ENTREGA_ID` int(11) NOT NULL DEFAULT '0',
  `DETALLE_ENTREGA` varchar(100) DEFAULT '',
  `OBSERVACIONES_ENTREGA` varchar(500) DEFAULT '',
  `CLIENTE_ID` int(11) NOT NULL DEFAULT '0',
  `CENTRO_ID` int(11) NOT NULL DEFAULT '0',
  `REPLACEMENT_ID` int(11) NOT NULL DEFAULT '0',
  `REFERENCIA_CLIENTE` varchar(800) DEFAULT NULL,
  `PRECIO` decimal(11,2) DEFAULT '0.00',
  `PRECIO_FIJADO` int(11) DEFAULT '0',
  `FECHA_PREV_FIN` date DEFAULT NULL,
  `OBSERVACIONES` varchar(2048) DEFAULT '',
  `ANALISIS_DUPLICADO` int(11) DEFAULT '0',
  `ANULADA` int(11) DEFAULT '0',
  `PRECINTO` varchar(100) DEFAULT '[NULL]',
  `BANO_ID` int(11) NOT NULL DEFAULT '0',
  `TIPO_FRECUENCIA_ID` int(11) NOT NULL DEFAULT '0',
  `IPA` int(11) NOT NULL DEFAULT '0',
  `INFORME_MANUAL` int(11) NOT NULL DEFAULT '0',
  `FECHA_RECOGIDA` timestamp NULL DEFAULT NULL,
  `FECHA_COMIENZO` date DEFAULT '0000-00-00',
  `FECHA_FINALIZACION` date DEFAULT '0000-00-00',
  `FECHA_CIERRE` date DEFAULT '0000-00-00',
  `HORA_CIERRE` varchar(10) DEFAULT '',
  `FECHA_ENVIO` timestamp NULL DEFAULT NULL,
  `MOTIVO_RETRASO_ID` int(11) DEFAULT '0',
  `RETRASO_OBSERVACION` text,
  `CERRADA` int(11) DEFAULT '0',
  `REVISION_USUARIO` int(11) DEFAULT '0',
  `CERRADA_USUARIO` int(11) DEFAULT '1',
  `DOCUMENTO_PAGO` int(11) DEFAULT '0',
  `IMPRESA` int(11) DEFAULT '0',
  `ENVIADO_CORREO` int(11) DEFAULT '0',
  `ULT_EDICION_IMP` int(11) DEFAULT '0',
  `OP_VUELO` int(11) DEFAULT '0',
  `OP_INSITU` int(11) DEFAULT '0',
  `OP_LABMOVIL` int(11) DEFAULT '0',
  `OP_NORUTINARIA` int(11) DEFAULT '0',
  `OP_REPETICION` int(11) DEFAULT '0',
  `SITUACION` int(11) DEFAULT '0',
  `FIRMA` int(11) NOT NULL DEFAULT '0',
  `PRODUCTO` varchar(255) NOT NULL DEFAULT '',
  `RESPONSABLE_ID` int(11) DEFAULT '0',
  `PEDIDO_ID` int(11) DEFAULT '0',
  `OFERTA_ID` int(11) DEFAULT '0',
  `PAQUETE_ID` int(11) DEFAULT '0',
  `ENAC` int(11) DEFAULT '0',
  `NADCAP` int(11) DEFAULT '0',
  `URGENTE` int(11) DEFAULT '0',
  `AJUSTE` int(11) DEFAULT '0',
  `CONSULTA` int(11) DEFAULT '0',
  `CONSULTA_OBSERVACIONES` text,
  `AGRUPADA` int(11) DEFAULT '0' COMMENT '1. MUESTRA AGRUPADA',
  `AGRUPADA_MUESTRA_ID` int(11) DEFAULT '0' COMMENT '0. MUESTRA RAIZ, XXXXX. APUNTA A MUESTRA RAIZ',
  PRIMARY KEY (`ID_MUESTRA`,`ID_PARTICULAR`,`ANNO`,`ID_GENERAL`,`BANO_ID`) USING BTREE,
  UNIQUE KEY `ID_MUESTRA` (`ID_MUESTRA`),
  KEY `UNICO` (`ID_MUESTRA`),
  KEY `CLIENTE` (`CLIENTE_ID`),
  KEY `TIPO_ANALISIS_ID` (`TIPO_ANALISIS_ID`),
  KEY `TIPO_MUESTRA_ID` (`TIPO_MUESTRA_ID`),
  KEY `PEDIDO_ID` (`PEDIDO_ID`),
  KEY `BANO_ID` (`BANO_ID`),
  KEY `AGRUPADA_MUESTRA_ID` (`AGRUPADA_MUESTRA_ID`),
  KEY `FECHA_CIERRE` (`FECHA_CIERRE`),
  KEY `ANNO` (`ANNO`),
  KEY `CENTRO_ID` (`CENTRO_ID`),
  KEY `FECHA_RECEPCION` (`FECHA_RECEPCION`),
  KEY `ANNO_CLIENTE_ID_ANULADA_DOCUMENTO_PAGO` (`ANNO`,`CLIENTE_ID`,`ANULADA`,`DOCUMENTO_PAGO`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='En DOCUMENTO_PAGO: 0 ninguno; 1 albaran; 2 factura';

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla geslab_canagrosa.usuarios
CREATE TABLE IF NOT EXISTS `usuarios` (
  `ID_EMPLEADO` int(11) NOT NULL DEFAULT '0',
  `NOMBRE` varchar(100) NOT NULL DEFAULT '',
  `APELLIDOS` varchar(100) NOT NULL DEFAULT '',
  `USUARIO` varchar(100) DEFAULT '',
  `PASSWORD` varchar(100) DEFAULT '',
  `PER_IMPRESION` int(11) NOT NULL DEFAULT '0',
  `PER_FACTURACION` int(11) NOT NULL DEFAULT '0',
  `PER_MODIFICACION` int(11) NOT NULL DEFAULT '0',
  `PER_ELIMINACION` int(11) NOT NULL DEFAULT '0',
  `PER_USUARIOS` int(11) NOT NULL DEFAULT '0',
  `PER_EDICION` int(11) NOT NULL DEFAULT '0',
  `PER_CIERRE` int(11) NOT NULL DEFAULT '0',
  `PER_PEDIDOS_REACTIVOS` int(11) DEFAULT '0',
  `PER_EMPLEADOS` int(11) DEFAULT '0',
  `PER_CONTABILIDAD` int(11) DEFAULT '0',
  `PER_ENVIO_PEDIDOS_PROVEEDOR` int(11) DEFAULT '0',
  `PER_DOCUMENTACION_CALIDAD` int(11) DEFAULT '0',
  `PER_PROYECTOS` int(11) DEFAULT '0',
  `PER_NC` int(11) DEFAULT '0',
  `PER_DATOS_ESPECIALES` int(11) DEFAULT '0',
  `USO` varchar(50) DEFAULT '',
  `FIRMA` varchar(250) NOT NULL DEFAULT '',
  `IMAGEN` varchar(250) NOT NULL DEFAULT '',
  `ANULADO` int(11) NOT NULL DEFAULT '0',
  `EMAIL` varchar(255) NOT NULL DEFAULT '',
  `FNMT_RUTA` varchar(255) NOT NULL DEFAULT '',
  `FNMT_PASS` varchar(50) NOT NULL DEFAULT '',
  `PER_PNT` int(11) DEFAULT '0',
  `PER_ADMIN_PNT` int(11) DEFAULT '0',
  `PER_MATRIZ_CUALIF` int(11) DEFAULT '0',
  `PER_VIDEOS` int(11) DEFAULT NULL,
  `PER_IMPRESION_PNT` int(11) DEFAULT '0',
  `PER_INCURRIDOS` int(11) DEFAULT '0',
  `PER_REVISION` int(11) DEFAULT '0',
  `PER_OFERTAS` int(11) DEFAULT '0',
  `PER_PLAZO_ENTREGA_CAMBIO` int(11) DEFAULT '0',
  `PER_PLAZO_ENTREGA_LISTADO` int(11) DEFAULT '0',
  `PER_INDICADORES_CLIENTE` int(11) DEFAULT '0',
  `PER_FAMILIAS_CA` int(11) DEFAULT '0',
  `REVISION_CARGO` varchar(150) DEFAULT '',
  `PER_TRAMITACION_CONTRATA` int(11) DEFAULT '0',
  `PER_RFI` int(11) DEFAULT '0',
  `PER_PFA` int(11) DEFAULT '0',
  `PER_SCG` int(11) DEFAULT '0',
  `PER_TESORERIA_MENU` int(11) DEFAULT '0',
  `PER_TESORERIA_FP` int(11) DEFAULT '0',
  `PER_NORMAS_NO_CONTROLADAS` int(11) DEFAULT '0',
  `PER_DES_PRODUCTO` int(11) DEFAULT '0',
  `PER_MOD_CLIENTE` int(11) DEFAULT '0',
  `PER_INCIDENCIAS` int(11) DEFAULT '0',
  `PER_PRODUCTIVIDAD` int(11) DEFAULT '0',
  `PASSWORD_MD5` varchar(250) DEFAULT '',
  `APP_OP` int(11) DEFAULT '0',
  `FECHA_CADUCIDAD` date DEFAULT NULL,
  PRIMARY KEY (`ID_EMPLEADO`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla geslab_canagrosa.vida
CREATE TABLE IF NOT EXISTS `vida` (
  `ID` int(11) NOT NULL DEFAULT '0',
  `TIPO_OBJETO` int(11) NOT NULL,
  `CODIGO_OBJETO` int(11) NOT NULL,
  `MENSAJE` varchar(500) NOT NULL,
  `TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `TIPO` (`TIPO_OBJETO`),
  KEY `CODIGO` (`CODIGO_OBJETO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- La exportación de datos fue deseleccionada.

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
